apiVersion: v1
kind: Service
metadata:
  name: newsapi-fetcher-service
spec:
  selector:
    app: newsapi-fetcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
